import assert from 'node:assert/strict';
// @ts-ignore Node's native TypeScript runner requires the explicit extension.
import { act, advance, start, view, type Room } from '../lib/game.ts';
const r: Room = { code: 'ABCDE', host: 'a', players: ['a', 'b'].map(id => ({ id, name: id, avatar: 0, score: 0, task: null, last: 0, completed: 0 })), phase: 'lobby', round: 0, end: 0, panel: { planet: 0, symbol: 0, power: false, dial: 0 }, feed: [], event: '', seed: 0 };
start(r, 1000);
assert.equal(r.round, 1);
assert.equal(r.end, 61000);
r.players[0].task = { kind: 'planet', target: 2, points: 10, text: 'Pink' };
r.players[1].task = { kind: 'symbol', target: 3, points: 10, text: 'Plus' };
act(r, r.players[0], 'planet', 2, 2000);
assert.equal(r.players[0].score, 10);
assert.equal(r.players[0].completed, 1);
act(r, r.players[0], 'planet', 2, 2000);
assert.equal(r.players[0].score, 10);
r.players[0].task = { kind: 'partner', target: 3, partner: 'b', points: 20, text: 'Partner' };
act(r, r.players[0], 'symbol', 3, 2300);
assert.equal(r.players[0].score, 10);
act(r, r.players[1], 'symbol', 3, 2500);
assert.equal(r.players[0].score, 30);
r.event = 'FREEZE';
act(r, r.players[0], 'planet', 1, 3000);
assert.equal(r.panel.planet, 2);
const v = view(r, 'a', 3000);
assert.equal(v.host, undefined);
assert.equal(v.players[1].task, null);
assert.equal(v.players[1].id, undefined);
assert.ok(v.players[0].task);
advance(r, 61000);
assert.equal(r.phase, 'results');
assert.ok(r.players.every(p => p.task === null));
r.round = 4;
start(r, 62000);
advance(r, 122000);
assert.equal(r.phase, 'finished');
console.log('Passed: server scoring, rate limiting, partner actions, freeze, privacy, timers, five-round ending.');
